import { useEffect, useState } from "react";
import { api, errorMessage, projectApi } from "../services/api";
import { ErrorNotice } from "./IntelligencePages";
type Dependency = { id: string; name: string; version: string; ecosystem: string; manifest: string; scope: string; direct: boolean; first_party: boolean; files: string[]; provenance: string; security: string };
export function DependenciesPage({ projectId, onFile }: { projectId: string; onFile: (path: string) => void }) {
 const [items, setItems] = useState<Dependency[]>([]); const [warnings, setWarnings] = useState<string[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [query, setQuery] = useState(""); const [ecosystem, setEcosystem] = useState(""); const [scope, setScope] = useState(""); const [revision, setRevision] = useState(0);
 useEffect(() => { const controller = new AbortController(); setBusy(true); setError(""); api<{ items: Dependency[]; warnings: string[] }>(`${projectApi(projectId)}/dependencies`, { signal: controller.signal }).then(v => { setItems(v.items); setWarnings(v.warnings); }).catch(e => { if (!controller.signal.aborted) setError(errorMessage(e)); }).finally(() => { if (!controller.signal.aborted) setBusy(false); }); return () => controller.abort(); }, [projectId, revision]);
 const visible = items.filter(d => (!ecosystem || d.ecosystem === ecosystem) && (!scope || (scope === "first_party" ? d.first_party : scope === "direct" ? d.direct && !d.first_party : !d.direct && !d.first_party)) && `${d.name} ${d.manifest}`.toLowerCase().includes(query.toLowerCase()));
 return <section className="intelligence-page"><div className="page-heading"><div><small>INTELLIGENCE / DÉPENDANCES</small><h1>Dépendances du projet</h1><p>Versions déclarées, résolutions des lockfiles et usages repérés dans les imports.</p></div><button onClick={() => setRevision(v => v + 1)} disabled={busy}>Actualiser</button></div><div className="finding-filters"><label>Recherche<input value={query} onChange={e => setQuery(e.target.value)} placeholder="Nom ou manifeste" /></label><label>Écosystème<select value={ecosystem} onChange={e => setEcosystem(e.target.value)}><option value="">Tous</option>{["npm", "composer", "cargo", "pub", "go", "python"].map(v => <option key={v}>{v}</option>)}</select></label><label>Périmètre<select value={scope} onChange={e => setScope(e.target.value)}><option value="">Tous</option><option value="first_party">Packages locaux explicites</option><option value="direct">Dépendances directes</option><option value="transitive">Résolutions indirectes</option></select></label></div><ErrorNotice error={error} retry={() => setRevision(v => v + 1)} />{busy && <p role="status">Lecture des manifestes et lockfiles…</p>}{warnings.length > 0 && <details className="intelligence-card"><summary>{warnings.length} limites de lecture</summary>{warnings.map((w, i) => <p key={i}>{w}</p>)}</details>}<p className="provenance">Les versions de manifeste sont des contraintes, celles des lockfiles des résolutions. Les imports ne prouvent pas une utilisation à l’exécution. Aucune base de vulnérabilités externe n’a été interrogée.</p>{!busy && !visible.length && <p>Aucune dépendance dans ce périmètre.</p>}<div className="dependency-list">{visible.map(d => <details key={d.id} className="intelligence-card"><summary><b>{d.name}</b> <code>{d.version}</code> · {d.ecosystem} · {d.first_party ? "local" : d.direct ? "direct" : "indirect / lockfile"}</summary><p><code>{d.manifest}</code> · {d.scope}</p><p>{d.provenance}</p><p>{d.security}</p><h3>Fichiers utilisant un import associé</h3>{d.files.length ? d.files.map(path => <button className="source-row" key={path} onClick={() => onFile(path)}>{path}</button>) : <p>Aucun import associé dans le graphe actuel.</p>}</details>)}</div></section>;
}
