import { useEffect, useState } from "react";
import { api, errorMessage, projectApi } from "../services/api";
import type { AtlasNode } from "../graphView";
import { ErrorNotice } from "./IntelligencePages";
type Candidate = { node: AtlasNode; score_lexical: number; score_symbol: number; score_semantic: number; score_graph: number; score_feature: number; score_final: number; reasons: string[] };
type IndexStats = { total: number; updated: number; reused: number; deleted: number; version: string };
export function HybridSearchPage({ projectId, onInspect, onFocus }: { projectId: string; onInspect: (id: string) => void; onFocus: (id: string) => void }) {
 const [query, setQuery] = useState(""); const [items, setItems] = useState<Candidate[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [stats, setStats] = useState<IndexStats | null>(null); const [revision, setRevision] = useState(0);
 useEffect(() => { const controller = new AbortController(); setError(""); setItems([]); if (!query.trim()) { setBusy(false); return; } setBusy(true); const timer = setTimeout(() => { api<{ items: Candidate[] }>(`${projectApi(projectId)}/intelligence/search?q=${encodeURIComponent(query)}&limit=50`, { signal: controller.signal }).then(result => setItems(result.items)).catch(e => { if (!controller.signal.aborted) setError(errorMessage(e)); }).finally(() => { if (!controller.signal.aborted) setBusy(false); }); }, 250); return () => { clearTimeout(timer); controller.abort(); }; }, [projectId, query, revision]);
 async function rebuild() { setBusy(true); setError(""); try { setStats(await api<IndexStats>(`${projectApi(projectId)}/intelligence/index`, { method: "POST" })); setRevision(v => v + 1); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
 return <section className="intelligence-page"><div className="page-heading"><div><small>INTELLIGENCE / RECHERCHE</small><h1>Retrouver du code</h1><p>Recherche exacte, symboles, chemins et concepts locaux. Les scores expliquent le classement.</p></div><button disabled={busy} onClick={() => void rebuild()}>Reconstruire l’index local</button></div><label className="search-field">Question, symbole ou chemin<input autoFocus aria-label="Rechercher du code" value={query} onChange={e => setQuery(e.target.value)} placeholder="Où est gérée la connexion utilisateur ?" /></label><p className="provenance">Vecteurs locaux déterministes, sans modèle neuronal ni clé API. Les similitudes sont des indices, pas des preuves.</p>{stats && <p role="status">{stats.total} unités · {stats.updated} recalculées · {stats.version}</p>}<ErrorNotice error={error} retry={() => setRevision(v => v + 1)} />{busy && <p role="status">Recherche et classement des candidats…</p>}{!busy && query && !items.length && !error && <p>Aucun résultat. Essayez un nom de fichier, de symbole ou un terme métier plus précis.</p>}{!query && <p>Commencez par une question ou un nom de symbole. L’index se met à jour lors des recherches.</p>}<div className="search-candidates">{items.map(hit => <article className="intelligence-card" key={hit.node.id}><div className="candidate-heading"><div><h2>{hit.node.name}</h2><code>{hit.node.path}</code><small>{hit.node.kind} · {hit.node.language} · L{hit.node.start_line ?? 1}–{hit.node.end_line ?? "?"}</small></div><b>{Math.round(hit.score_final * 100)} / 100</b></div><div className="inline-form"><button onClick={() => onInspect(hit.node.id)}>Ouvrir le code</button><button onClick={() => onFocus(hit.node.id)}>Focaliser le graphe</button></div><details><summary>Pourquoi ce résultat ?</summary><dl className="score-breakdown">{([['Lexical', hit.score_lexical], ['Symbole', hit.score_symbol], ['Vecteur local', hit.score_semantic], ['Graphe', hit.score_graph], ['Feature', hit.score_feature]] as const).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value.toFixed(3)}</dd></div>)}</dl>{hit.reasons.map((reason, i) => <p key={i}>{reason}</p>)}</details></article>)}</div></section>;
}
