import { useEffect, useState } from "react";
import type { AtlasNode } from "../graphView";
import { api, errorMessage, projectApi } from "../services/api";
type Feature = { id: string; name: string };
export type TestPlan = { feature: string | null; existing_tests: AtlasNode[]; scenarios: { name: string; kind: string; status: string; evidence: string[]; priority: string }[]; risks: string[]; generated_files: { path: string; content: string }[]; coverage: number | null; provenance: string };
export type Estimate = { summary: string; affected_features: string[]; affected_nodes: AtlasNode[]; affected_files: string[]; breakdown: { category: string; minimum: number; likely: number; maximum: number }[]; unknowns: string[]; risk_level: string; confidence: number; provenance: string };
export type Diff = { branch: string; branches: string[]; files: { path: string; nodes: string[]; features: string[]; lines: { kind: string; text: string; old_line: number | null; new_line: number | null }[] }[]; warnings: string[] };
export function ErrorNotice({ error, retry }: { error: string; retry: () => void }) { return error ? <div className="intelligence-error" role="alert"><strong>Impossible de terminer l’opération</strong><p>{error}</p><button onClick={retry}>Réessayer</button></div> : null; }
function download(path: string, content: string) { const url = URL.createObjectURL(new Blob([content], { type: "text/plain" })); const link = document.createElement("a"); link.href = url; link.download = path.split("/").pop()!; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
export function TestsPage({ projectId, features, seed, onInspect }: { projectId: string; features: Feature[]; seed: string; onInspect: (id: string) => void }) {
  const [feature, setFeature] = useState(seed); const [plan, setPlan] = useState<TestPlan | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [revision, setRevision] = useState(0);
  useEffect(() => setFeature(seed), [seed]);
  useEffect(() => { const controller = new AbortController(); setBusy(true); setError(""); setPlan(null); api<TestPlan>(`${projectApi(projectId)}/tests/plan${feature ? `?feature_id=${encodeURIComponent(feature)}` : ""}`, { signal: controller.signal }).then(setPlan).catch(e => { if (!controller.signal.aborted) setError(errorMessage(e)); }).finally(() => { if (!controller.signal.aborted) setBusy(false); }); return () => controller.abort(); }, [projectId, feature, revision]);
  return <section className="intelligence-page"><div className="page-heading"><div><small>INTELLIGENCE / TESTS</small><h1>Tests & scénarios</h1><p>Relier les tests existants aux points d’entrée et préparer les vérifications manquantes.</p></div><select aria-label="Feature à tester" value={feature} onChange={e => setFeature(e.target.value)}><option value="">Projet entier</option>{features.map(f => <option key={f.id} value={f.id}>{f.name}</option>)}</select></div><ErrorNotice error={error} retry={() => setRevision(v => v + 1)} />{busy && <p role="status">Inspection des tests et des points d’entrée…</p>}{plan && <><div className="intelligence-metrics"><div><b>{plan.existing_tests.length}</b><span>Éléments de test repérés</span></div><div><b>{plan.scenarios.length}</b><span>Scénarios proposés</span></div><div><b>{plan.coverage === null ? "Inconnue" : `${plan.coverage}%`}</b><span>Couverture fonctionnelle vérifiée</span></div></div><p className="provenance">{plan.provenance}</p><div className="intelligence-columns"><section><h2>Scénarios à vérifier</h2>{!plan.scenarios.length && <p>Aucun point d’entrée exploitable détecté. Choisissez une autre Feature ou analysez ses routes.</p>}{plan.scenarios.map((s, i) => <article className="intelligence-card" key={i}><h3>{s.name}</h3><small>{s.kind} · priorité {s.priority}</small><p>{s.status === "missing_evidence" ? "Aucune preuve de test lié" : "Test lié — assertions non vérifiées"}</p>{s.evidence.map(id => <button key={id} onClick={() => onInspect(id)}>Ouvrir le test</button>)}</article>)}</section><section><h2>Tests existants</h2>{!plan.existing_tests.length && <p>Aucun test relié au périmètre par le graphe.</p>}{plan.existing_tests.map(n => <button className="source-row" key={n.id} onClick={() => onInspect(n.id)}><b>{n.name}</b><small>{n.path}</small></button>)}<h2>Limites & risques</h2>{plan.risks.map(r => <p key={r}>{r}</p>)}</section></div><h2>Fichiers Playwright proposés</h2>{!plan.generated_files.length && <p>Aucune route statique de navigation exploitable. Aucun sélecteur ni chemin n’a été inventé.</p>}{plan.generated_files.map(file => <details key={file.path} className="intelligence-card"><summary>{file.path}</summary><pre>{file.content}</pre><button onClick={() => download(file.path, file.content)}>Télécharger le test</button></details>)}</>}</section>;
}
export function EstimatePage({ projectId, seed, onInspect }: { projectId: string; seed: string; onInspect: (id: string) => void }) {
  const [task, setTask] = useState(seed); const [value, setValue] = useState<Estimate | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { setTask(seed); setValue(null); }, [seed, projectId]);
  async function estimate() { setBusy(true); setError(""); setValue(null); try { setValue(await api<Estimate>(`${projectApi(projectId)}/estimates`, { method: "POST", body: JSON.stringify({ task }) })); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <section className="intelligence-page"><div className="page-heading"><div><small>INTELLIGENCE / ESTIMATION</small><h1>Estimer une modification</h1><p>Un périmètre sourcé et une fourchette de travail à affiner avec votre équipe.</p></div></div><form className="estimate-form" onSubmit={e => { e.preventDefault(); void estimate(); }}><label htmlFor="estimate-task">Mission</label><textarea id="estimate-task" value={task} maxLength={8000} onChange={e => setTask(e.target.value)} placeholder="Ajouter l’authentification à deux facteurs…" /><button disabled={busy || !task.trim()}>{busy ? "Analyse du périmètre…" : "Estimer"}</button></form><ErrorNotice error={error} retry={() => void estimate()} />{value && <><p className="provenance">{value.provenance}</p><div className="intelligence-metrics"><div><b>{value.affected_files.length}</b><span>Fichiers candidats</span></div><div><b>{Math.round(value.confidence * 100)}%</b><span>Confiance heuristique</span></div><div><b>{value.risk_level}</b><span>Risque</span></div></div>{value.breakdown.length ? <div className="table-scroll"><table><caption>Heures de travail estimées — modèle heuristique non calibré</caption><thead><tr><th>Activité</th><th>Minimum</th><th>Probable</th><th>Maximum</th></tr></thead><tbody>{value.breakdown.map(row => <tr key={row.category}><th>{row.category}</th><td>{row.minimum.toFixed(1)} h</td><td>{row.likely.toFixed(1)} h</td><td>{row.maximum.toFixed(1)} h</td></tr>)}<tr><th>Total</th>{(["minimum", "likely", "maximum"] as const).map(key => <td key={key}>{value.breakdown.reduce((sum, row) => sum + row[key], 0).toFixed(1)} h</td>)}</tr></tbody></table></div> : <p>Aucun périmètre suffisamment pertinent trouvé pour chiffrer cette mission.</p>}<div className="intelligence-columns"><section><h2>Éléments à examiner</h2>{value.affected_nodes.map(n => <button className="source-row" key={n.id} onClick={() => onInspect(n.id)}><b>{n.name}</b><small>{n.path}</small></button>)}</section><section><h2>Hypothèses & inconnues</h2>{value.unknowns.map(u => <p key={u}>{u}</p>)}</section></div></>}</section>;
}
export function GitPage({ projectId, onInspect }: { projectId: string; onInspect: (id: string) => void }) {
  const [base, setBase] = useState(""); const [head, setHead] = useState(""); const [value, setValue] = useState<Diff | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function load(signal?: AbortSignal) { setBusy(true); setError(""); setValue(null); try { setValue(await api<Diff>(`${projectApi(projectId)}/git/diff?${new URLSearchParams({ base, head })}`, { signal })); } catch (e) { if (!signal?.aborted) setError(errorMessage(e)); } finally { if (!signal?.aborted) setBusy(false); } }
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [projectId]);
  return <section className="intelligence-page"><div className="page-heading"><div><small>INTELLIGENCE / GIT</small><h1>Revue des changements</h1><p>{value ? `Branche ${value.branch}` : "Diff Git en lecture seule"} · Comparez le travail en cours, des branches ou des commits.</p></div></div><form className="git-form" onSubmit={e => { e.preventDefault(); void load(); }}><label>Base<input list="git-branches" value={base} onChange={e => setBase(e.target.value)} placeholder="HEAD (par défaut)" /></label><label>Cible<input list="git-branches" value={head} onChange={e => setHead(e.target.value)} placeholder="Répertoire de travail" /></label><datalist id="git-branches">{value?.branches.map(b => <option key={b} value={b} />)}</datalist><button disabled={busy}>Comparer</button></form><ErrorNotice error={error} retry={() => void load()} />{busy && <p role="status">Lecture du diff Git…</p>}{value && <>{value.warnings.map(w => <p className="provenance" key={w}>{w}</p>)}<h2>{value.files.length} fichiers modifiés</h2>{!value.files.length && <p>Aucune différence textuelle suivie dans ce périmètre.</p>}{value.files.map(file => <details className="diff-file" key={file.path} open={value.files.length < 4}><summary>{file.path} · {file.nodes.length} symboles candidats · {file.features.length} Features</summary><div className="diff-actions">{file.nodes.slice(0, 8).map(id => <button key={id} onClick={() => onInspect(id)}>Ouvrir {id.split(":").pop()}</button>)}</div><div className="diff-lines">{file.lines.map((line, i) => <div key={i} className={`diff-line ${line.kind}`}><span>{line.old_line ?? ""}</span><span>{line.new_line ?? ""}</span><code>{line.text}</code></div>)}</div></details>)}</>}</section>;
}
