import { useEffect, useRef, useState } from "react";
import { api, errorMessage, projectApi } from "../../services/api";
import type { AtlasNode } from "../../graphView";
import type { UiAction } from "./types";
export function CommandPalette({ projectId, projects, features, onProject, onAction, onAssistant, onClose }: { projectId: string; projects: { id: string; name: string }[]; features: { id: string; name: string }[]; onProject: (id: string) => void; onAction: (action: UiAction) => Promise<void>; onAssistant: () => void; onClose: () => void }) {
  const [query, setQuery] = useState(""); const [hits, setHits] = useState<AtlasNode[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const root = useRef<HTMLElement>(null);
  useEffect(() => { const previous = document.activeElement as HTMLElement | null; return () => previous?.focus(); }, []);
  useEffect(() => { const controller = new AbortController(); setHits([]); setError(""); if (!projectId || !query.trim()) { setBusy(false); return; } setBusy(true); const timer = setTimeout(() => { api<{ items: { node: AtlasNode }[] }>(`${projectApi(projectId)}/intelligence/search?q=${encodeURIComponent(query)}&limit=12`, { signal: controller.signal }).then(v => setHits(v.items.map(h => h.node))).catch(e => { if (!controller.signal.aborted) setError(errorMessage(e)); }).finally(() => { if (!controller.signal.aborted) setBusy(false); }); }, 250); return () => { clearTimeout(timer); controller.abort(); }; }, [query, projectId]);
  async function run(action: UiAction) { try { await onAction(action); onClose(); } catch (e) { setError(errorMessage(e)); } }
  const pages = [["map", "Carte"], ["flow", "Flux"], ["search", "Recherche"], ["security", "Sécurité"], ["quality", "Qualité"], ["api", "API"], ["tests", "Tests"], ["estimate", "Estimation"], ["git", "Git"], ["docs", "Documentation"], ["dependencies", "Dépendances"]];
  return <div className="modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) onClose(); }}><section ref={root} className="command-palette" role="dialog" aria-modal="true" aria-label="Palette de commandes" onKeyDown={e => { if (e.key === "Escape") onClose(); if (e.key === "Tab") { const elements = Array.from(root.current?.querySelectorAll<HTMLElement>('input, button:not(:disabled)') ?? []); const index = elements.indexOf(document.activeElement as HTMLElement); e.preventDefault(); elements[(index + (e.shiftKey ? -1 : 1) + elements.length) % elements.length]?.focus(); } }}><div className="inline-form"><input autoFocus aria-label="Rechercher une commande ou du code" value={query} onChange={e => setQuery(e.target.value)} placeholder="Fichier, symbole, Feature, commande…" /><button onClick={onClose} aria-label="Fermer la palette">Esc</button></div><div className="command-results">{error && <p role="alert">{error}</p>}{busy && <p role="status">Recherche…</p>}{hits.map(n => <button key={n.id} onClick={() => void run({ type: "OPEN_NODE", node_id: n.id })}><b>{n.name}</b><small>{n.kind} · {n.path}</small></button>)}{features.filter(f => f.name.toLowerCase().includes(query.toLowerCase())).slice(0, 8).map(f => <button key={f.id} onClick={() => void run({ type: "OPEN_FEATURE", feature_id: f.id })}>Feature · {f.name}</button>)}{pages.filter(([, label]) => label.toLowerCase().includes(query.toLowerCase())).map(([page, label]) => <button key={page} disabled={!projectId} onClick={() => void run({ type: "NAVIGATE_PAGE", page })}>Ouvrir {label}</button>)}{projects.filter(p => p.name.toLowerCase().includes(query.toLowerCase())).map(p => <button key={p.id} onClick={() => { onProject(p.id); onClose(); }}>Projet · {p.name}</button>)}<button disabled={!projectId} onClick={() => { onAssistant(); onClose(); }}>Demander à l’assistant</button>{query && !busy && !hits.length && <p>Aucun symbole trouvé pour cette recherche.</p>}</div></section></div>;
}
