import { test, expect } from '@playwright/test';
import { realpathSync, mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
let root: string;
let projectId: string;
test.beforeAll(async () => {
 root = realpathSync(mkdtempSync(join(tmpdir(), 'atlas-e2e-')));
 mkdirSync(join(root, 'app/login'), { recursive: true });
 mkdirSync(join(root, 'app/api/login'), { recursive: true });
 writeFileSync(join(root, 'app/login/page.tsx'), 'export default function LoginPage() { return <form><label>Email<input name="email" placeholder="Email" /></label><button type="submit">Se connecter</button></form>; }\n');
 writeFileSync(join(root, 'app/api/login/route.ts'), 'export async function POST(request: Request) { const body = await request.json(); return Response.json({ authenticated: Boolean(body.email) }); }\n');
 writeFileSync(join(root, 'auth.ts'), 'export function login(email: string) { return email.length > 0; }\n');
 execFileSync('git', ['init', root]); execFileSync('git', ['-C', root, 'add', '.']); execFileSync('git', ['-C', root, '-c', 'user.name=Atlas test', '-c', 'user.email=test@example.invalid', 'commit', '-m', 'fixture']);
 writeFileSync(join(root, 'auth.ts'), 'export function login(email: string) { return email.includes("@"); }\n');
});
test.afterAll(async ({ request }) => { if (projectId) await request.delete(`/api/projects/${projectId}`); rmSync(root, { recursive: true, force: true }); });
test('analyze, graph, features, source, assistant, tests, estimate and Git form one workspace', async ({ page, request }) => {
 const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
 await page.goto('/');
 await page.getByPlaceholder('Choisir un dossier de projet').fill(root);
 await page.getByRole('button', { name: 'Analyser', exact: true }).click();
 await expect(page.getByRole('complementary', { name: 'Assistant projet' })).toBeVisible();
 const projects = await (await request.get('/api/projects')).json(); projectId = projects.find((p: { root: string }) => p.root === root).id;
 await expect(page.locator('.react-flow')).toBeVisible();
 await page.getByRole('navigation', { name: 'Navigation principale' }).getByRole('button', { name: 'Features', exact: true }).click();
 const detect = page.getByRole('button', { name: /Détecter/ }).first(); if (await detect.isVisible()) { await detect.click(); }
 await expect(page.getByRole('button', { name: 'Inspecter', exact: true }).first()).toBeVisible();
 await page.getByRole('button', { name: 'Inspecter', exact: true }).first().click();
 await page.getByRole('button', { name: 'Code source', exact: true }).click();
 await expect(page.locator('.modal-backdrop')).toBeVisible(); await page.keyboard.press('Escape');
 await page.getByRole('button', { name: 'Palette de commandes' }).click();
 await page.getByRole('textbox', { name: 'Rechercher une commande ou du code' }).fill('login');
 await expect(page.getByRole('dialog', { name: 'Palette de commandes' }).getByRole('button', { name: /^login/ }).first()).toBeVisible();
 await page.getByRole('dialog', { name: 'Palette de commandes' }).getByRole('button', { name: /^login/ }).first().click();
 await expect(page.getByRole('dialog')).toBeVisible(); await page.keyboard.press('Escape');
 await page.getByLabel('Votre question').fill('Montre-moi comment fonctionne la connexion.');
 await page.getByRole('button', { name: 'Envoyer', exact: true }).click();
 await expect(page.locator('.chat-message.assistant')).toHaveCount(1);
 await expect(page.getByRole('dialog')).toBeVisible(); await page.keyboard.press('Escape');
 await page.getByRole('button', { name: 'Quels tests manquent ?', exact: true }).click();
 await expect(page.getByRole('heading', { name: 'Tests & scénarios' })).toBeVisible();
 await expect(page.getByText('Couverture fonctionnelle vérifiée')).toBeVisible();
 const nav = page.getByRole('navigation', { name: 'Navigation principale' });
 await nav.getByRole('button', { name: 'Estimation', exact: true }).click();
 await page.getByLabel('Mission', { exact: true }).fill('Modifier login pour ajouter du 2FA');
 await page.getByRole('button', { name: 'Estimer', exact: true }).click();
 await expect(page.getByRole('table')).toBeVisible();
 await nav.getByRole('button', { name: 'Git', exact: true }).click();
 await expect(page.getByText('auth.ts', { exact: false }).first()).toBeVisible();
 await expect(page.locator('.diff-line.added')).not.toHaveCount(0);
 await nav.getByRole('button', { name: 'API', exact: true }).click();
 await expect(page.locator('.api-tree').getByText('/api/login', { exact: false }).first()).toBeVisible();
 await expect(page.getByRole('heading', { name: 'Tests & scénarios' })).toHaveCount(0);
 await expect(page.getByRole('heading', { name: 'Revue des changements' })).toHaveCount(0);
 for (const name of ['Sécurité', 'Qualité', 'Documentation', 'Mon code', 'Bibliothèque', 'MCP', 'Flux', 'Recherche']) { await nav.getByRole('button', { name, exact: true }).click(); await expect(page.locator('main')).toBeVisible(); }
 await page.screenshot({ path: '../output/playwright/workspace.png', fullPage: true });
 expect(errors).toEqual([]);
});
